export { default as Header} from './header/Header'
export { default as Footer} from './footer/Footer'
export { default as VideoCarsoul } from './videocal/VideoCarsoul'
export { default as Astrologers } from './astrologers/Astrologers'
export { default as ManyPOS } from './manyPOS/ManyPOS'
export { default as Review } from './review/Review'